// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';
import {terminal} from '../models';
import {config} from '../models';
import {worktree} from '../models';
import {main} from '../models';

export function AttachSession(arg1:string):Promise<void>;

export function CleanupWorktree(arg1:string,arg2:boolean):Promise<void>;

export function CreateSession(arg1:string,arg2:boolean,arg3:string):Promise<session.SessionInfo>;

export function CreateTerminal(arg1:string):Promise<terminal.TerminalInfo>;

export function DismissNotification(arg1:string):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetFileDiff(arg1:string,arg2:string):Promise<worktree.FileDiff>;

export function GetSessionDiff(arg1:string):Promise<Array<worktree.FileDiff>>;

export function GetWorktreeStatus(arg1:string):Promise<main.WorktreeStatusResult>;

export function IsGitRepo(arg1:string):Promise<boolean>;

export function KillSession(arg1:string):Promise<void>;

export function KillTerminal(arg1:string):Promise<void>;

export function ListSessions():Promise<Array<session.SessionInfo>>;

export function MergeSession(arg1:string):Promise<worktree.MergeResult>;

export function PickDirectory():Promise<string>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function RespondToNotification(arg1:string,arg2:string):Promise<void>;

export function SetConfig(arg1:config.Config):Promise<void>;
