// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';
import {terminal} from '../models';
import {config} from '../models';

export function AttachSession(arg1:string):Promise<void>;

export function CreateSession(arg1:string):Promise<session.SessionInfo>;

export function CreateTerminal(arg1:string):Promise<terminal.TerminalInfo>;

export function DismissNotification(arg1:string):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function KillSession(arg1:string):Promise<void>;

export function KillTerminal(arg1:string):Promise<void>;

export function ListSessions():Promise<Array<session.SessionInfo>>;

export function PickDirectory():Promise<string>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function RespondToNotification(arg1:string,arg2:string):Promise<void>;

export function SetConfig(arg1:config.Config):Promise<void>;
