// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';
import {config} from '../models';

export function CreateSession(arg1:string):Promise<session.SessionInfo>;

export function GetConfig():Promise<config.Config>;

export function KillSession(arg1:string):Promise<void>;

export function PickDirectory():Promise<string>;

export function ListSessions():Promise<Array<session.SessionInfo>>;

export function SetConfig(arg1:config.Config):Promise<void>;
