// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AttachSession(arg1) {
  return window['go']['main']['App']['AttachSession'](arg1);
}

export function CreateSession(arg1) {
  return window['go']['main']['App']['CreateSession'](arg1);
}

export function CreateTerminal(arg1) {
  return window['go']['main']['App']['CreateTerminal'](arg1);
}

export function DismissNotification(arg1) {
  return window['go']['main']['App']['DismissNotification'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function KillSession(arg1) {
  return window['go']['main']['App']['KillSession'](arg1);
}

export function KillTerminal(arg1) {
  return window['go']['main']['App']['KillTerminal'](arg1);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function RespondToNotification(arg1, arg2) {
  return window['go']['main']['App']['RespondToNotification'](arg1, arg2);
}

export function SetConfig(arg1) {
  return window['go']['main']['App']['SetConfig'](arg1);
}
